global:
  resolve_timeout: 5m

route:
  receiver: "default-notification"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: "default-notification"
    webhook_configs:
      - url: "https://notification.example.com/webhook"
        send_resolved: true